from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import json
from pathlib import Path

WORKSPACE_FORMAT = "facestudio-builder-workspace-v1"

STAGES = (
    "home", "project", "source_photo", "landmarks", "geometry",
    "donor_search", "donor_review", "uv_calibration", "reconstruction",
    "refinement", "validation", "preview", "export", "settings",
)


@dataclass
class StageState:
    status: str = "not-started"
    detail: str = ""

    def normalised(self) -> "StageState":
        allowed = {"not-started", "needs-review", "running", "complete", "blocked"}
        return StageState(self.status if self.status in allowed else "not-started", str(self.detail))


@dataclass
class BuilderWorkspace:
    project_name: str = "Untitled Face"
    workspace_directory: str = ""
    source_photo: str = ""
    portrait_record: str = ""
    geometry_dataset: str = ""
    donor_player_id: str = ""
    donor_manifest: str = ""
    uv_record: str = ""
    reconstruction_manifest: str = ""
    refinement_manifest: str = ""
    validation_report: str = ""
    integrated_manifest: str = ""
    export_directory: str = ""
    stages: dict[str, StageState] = field(default_factory=lambda: {name: StageState() for name in STAGES})
    updated_at: str = ""

    def __post_init__(self) -> None:
        for name in STAGES:
            value = self.stages.get(name, StageState())
            if isinstance(value, dict):
                value = StageState(**value)
            self.stages[name] = value.normalised()
        self.refresh()

    def refresh(self) -> None:
        integrated = self._exists(self.integrated_manifest)
        self._set("home", "complete", "Workspace ready")
        self._set("project", "complete" if self.workspace_directory else "needs-review", self.project_name)
        self._path_stage("source_photo", self.source_photo, "Choose a clear front-facing photograph")
        self._path_stage("landmarks", self.portrait_record, "Create or select a corrected landmark record")
        self._path_stage("geometry", self.geometry_dataset, "Measure geometry or select a reviewed dataset")
        donor_ready = bool(self.donor_player_id and self.donor_manifest)
        self._set("donor_search", "complete" if donor_ready else "needs-review", self.donor_player_id or "Search and select a donor")
        self._set("donor_review", "complete" if donor_ready else "blocked", "Locked donor" if donor_ready else "Requires donor search")
        self._path_stage("uv_calibration", self.uv_record, "Review all donor UV anchors")
        self._path_stage("reconstruction", self.reconstruction_manifest, "Run triangulated reconstruction")
        self._path_stage("refinement", self.refinement_manifest, "Run texture refinement")
        validation_ready = integrated or self._exists(self.validation_report)
        self._set("validation", "complete" if validation_ready else "needs-review", self.validation_report or ("Recorded in integrated build" if integrated else "Run texture validation"))
        preview_ready = integrated or self._exists(self.refinement_manifest)
        self._set("preview", "complete" if preview_ready else "blocked", "Build comparison available" if preview_ready else "Requires refined texture")
        self._set("export", "complete" if integrated else "blocked", self.export_directory or ("Package exported" if integrated else "Requires a completed build"))
        self._set("settings", "complete", "Application settings available")
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def mark_running_from(self, stage: str) -> None:
        start = STAGES.index(stage)
        for name in STAGES[start:]:
            if name == "settings":
                continue
            self._set(name, "running" if name == stage else "not-started", "Build pipeline running" if name == stage else "Awaiting previous stage")
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def record_integrated_build(self, manifest: Path, validation_report: Path | None = None) -> None:
        self.integrated_manifest = str(manifest)
        self.export_directory = str(manifest.parent)
        if validation_report:
            self.validation_report = str(validation_report)
        self._set("reconstruction", "complete", "Generated by integrated build")
        self._set("refinement", "complete", "Generated by integrated build")
        self._set("validation", "complete", "Validation report generated")
        self._set("preview", "complete", "Final texture available")
        self._set("export", "complete", str(manifest.parent))
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def save(self, path: Path) -> Path:
        self.refresh()
        payload = asdict(self); payload["format"] = WORKSPACE_FORMAT
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        return path

    @classmethod
    def load(cls, path: Path) -> "BuilderWorkspace":
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"Could not read FaceStudio workspace: {exc}") from exc
        if payload.pop("format", None) != WORKSPACE_FORMAT:
            raise ValueError(f"Expected {WORKSPACE_FORMAT}.")
        return cls(**payload)

    @property
    def progress(self) -> int:
        counted = [name for name in STAGES if name not in {"home", "settings"}]
        return round(sum(self.stages[name].status == "complete" for name in counted) / len(counted) * 100)

    def _path_stage(self, name: str, value: str, empty_detail: str) -> None:
        valid = self._exists(value)
        self._set(name, "complete" if valid else "needs-review", value if valid else empty_detail)

    @staticmethod
    def _exists(value: str) -> bool:
        return bool(value and Path(value).expanduser().exists())

    def _set(self, name: str, status: str, detail: str) -> None:
        self.stages[name] = StageState(status, detail)
